### PR TITLE
Faruk added trial2, let's review and merge

### PR DESCRIPTION
**Pull request by Taran522**
successful hopefully

### CODE REVIEW

**Review by YuliiaRublenko — CHANGES_REQUESTED** [review]
change code plz

**Comment by Taran522** [comment]
> change code plz

which particular part?

**Comment by ahmets34** [comment]
nice code

**Review by ahmets34 — APPROVED** [review]

**Review by ShaazShaaz — APPROVED** [review]

**Comment by Taran522** [comment]
> change code plz

I fixed the code, check it out

**Review by ShaazShaaz — APPROVED** [review]

**Review by AleksPet — APPROVED** [review]

**Review by YuliiaRublenko — APPROVED** [review]

**Pull request merged**
