### PR TITLE
important update

### PR DESCRIPTION
**Pull request by ShaazShaaz**
second check

### CODE REVIEW

**Review by Taran522 — CHANGES_REQUESTED** [review]
some changes need to be made before approval

**Review by YuliiaRublenko — APPROVED** [review]
acceptable

**Comment by Taran522** [comment]
let's have some conversation on this before approval (for practice

**Comment by YuliiaRublenko** [comment]
good idea to practice chating! I think it would be great for everyone to create a separate package and work there(to avoid conflicts)

**Review by ozodi — APPROVED** [review]

**Review by Taran522 — APPROVED** [review]

**Pull request merged**
