### PR TITLE
Package name changed 

### PR DESCRIPTION
**Pull request by Taran522**

### CODE REVIEW

**Comment by Taran522** [comment]
I changed the package name and re-opened a pull request. @YuliiaRublenko

**Review by YuliiaRublenko — CHANGES_REQUESTED** [review]
Ok, I see you opened a new pull request with the changes!
Please, update the package name accordingly to the java package naming rules :)

**Comment by Taran522** [comment]
I am about to adjust this request again.

**Comment by Taran522** [comment]
I just adjusted the package name as "b23_Group10_Faruk". Could you please confirm that you see the change?

**Review by YuliiaRublenko — APPROVED** [review]
very good! code is ready to be merged into master!

**Comment by YuliiaRublenko** [comment]
I see the changes! great job!

**Pull request merged**
