### PR TITLE
Faruk added "Forgot Password" function

### PR DESCRIPTION
**Pull request by Taran522**

### CODE REVIEW

**Review by YuliiaRublenko — CHANGES_REQUESTED** [review]
please follow the rules of naming a package. 
(sorry, just wanted to request some changes - the only thing I could think of was package name !)

**Comment by Taran522** [comment]
we are having access issues to Group 10

**Comment by Taran522** [comment]
I agree with you, Yuliia. Package names should be consistent. I will make the necessary adjustments.

**Review by YuliiaRublenko — CHANGES_REQUESTED** [review]
This looks better(I think everyone should create one package like that), but what I meant was the package name should always start from the lower case.

**Comment by YuliiaRublenko** [comment]
why did you close it?

**Comment by Taran522** [comment]
> why did you close it?

I got confused on making changes on the pull request once a change is required. How do I do that?

**Pull request closed without merging**
